// v3/dark/vue/application-ui/elements/buttons/Rounded secondary buttons.vue
<template>
  <button type="button" class="rounded-full bg-white/10 px-2.5 py-1 text-xs font-semibold text-white ring-1 ring-inset ring-white/5 hover:bg-white/20">Button text</button>
  <button type="button" class="rounded-full bg-white/10 px-2.5 py-1 text-sm font-semibold text-white ring-1 ring-inset ring-white/5 hover:bg-white/20">Button text</button>
  <button type="button" class="rounded-full bg-white/10 px-3 py-1.5 text-sm font-semibold text-white ring-1 ring-inset ring-white/5 hover:bg-white/20">Button text</button>
  <button type="button" class="rounded-full bg-white/10 px-3.5 py-2 text-sm font-semibold text-white ring-1 ring-inset ring-white/5 hover:bg-white/20">Button text</button>
  <button type="button" class="rounded-full bg-white/10 px-4 py-2.5 text-sm font-semibold text-white ring-1 ring-inset ring-white/5 hover:bg-white/20">Button text</button>
</template>

// v3/dark/react/application-ui/elements/buttons/Rounded secondary buttons.jsx
export default function Example() {
  return (
    <>
      <button
        type="button"
        className="rounded-full bg-white/10 px-2.5 py-1 text-xs font-semibold text-white ring-1 ring-inset ring-white/5 hover:bg-white/20"
      >
        Button text
      </button>
      <button
        type="button"
        className="rounded-full bg-white/10 px-2.5 py-1 text-sm font-semibold text-white ring-1 ring-inset ring-white/5 hover:bg-white/20"
      >
        Button text
      </button>
      <button
        type="button"
        className="rounded-full bg-white/10 px-3 py-1.5 text-sm font-semibold text-white ring-1 ring-inset ring-white/5 hover:bg-white/20"
      >
        Button text
      </button>
      <button
        type="button"
        className="rounded-full bg-white/10 px-3.5 py-2 text-sm font-semibold text-white ring-1 ring-inset ring-white/5 hover:bg-white/20"
      >
        Button text
      </button>
      <button
        type="button"
        className="rounded-full bg-white/10 px-4 py-2.5 text-sm font-semibold text-white ring-1 ring-inset ring-white/5 hover:bg-white/20"
      >
        Button text
      </button>
    </>
  )
}
