// v4/dark/react/application-ui/forms/input-groups/Input with disabled state.jsx
export default function Example() {
  return (
    <div>
      <label htmlFor="email" className="block text-sm/6 font-medium text-white">
        Email
      </label>
      <div className="mt-2">
        <input
          defaultValue="you@example.com"
          id="email"
          name="email"
          type="email"
          disabled
          placeholder="you@example.com"
          className="block w-full rounded-md bg-white/5 px-3 py-1.5 text-gray-300 outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 disabled:cursor-not-allowed disabled:bg-white/10 disabled:text-gray-500 disabled:outline-white/5 sm:text-sm/6"
        />
      </div>
    </div>
  )
}

// v3/dark/vue/application-ui/forms/input-groups/Input with disabled state.vue
<template>
  <div>
    <label for="email" class="block text-sm/6 font-medium text-white">Email</label>
    <div class="mt-2">
      <input type="email" name="email" id="email" value="you@example.com" disabled="" class="block w-full rounded-md bg-white/5 px-3 py-1.5 text-gray-300 outline outline-1 -outline-offset-1 outline-white/10 placeholder:text-gray-500 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-500 disabled:cursor-not-allowed disabled:bg-white/10 disabled:text-gray-500 disabled:outline-white/5 sm:text-sm/6" placeholder="you@example.com" />
    </div>
  </div>
</template>
