// v4/light/vue/application-ui/headings/card-headings/With action.vue
<template>
  <div class="border-b border-gray-200 px-4 py-5 sm:px-6">
    <div class="-mt-2 -ml-4 flex flex-wrap items-center justify-between sm:flex-nowrap">
      <div class="mt-2 ml-4">
        <h3 class="text-base font-semibold text-gray-900">Job Postings</h3>
      </div>
      <div class="mt-2 ml-4 shrink-0">
        <button type="button" class="relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-xs hover:bg-indigo-500 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">Create new job</button>
      </div>
    </div>
  </div>
</template>

// v3/light/react/application-ui/headings/card-headings/With action.jsx
export default function Example() {
  return (
    <div className="border-b border-gray-200 px-4 py-5 sm:px-6">
      <div className="-ml-4 -mt-2 flex flex-wrap items-center justify-between sm:flex-nowrap">
        <div className="ml-4 mt-2">
          <h3 className="text-base font-semibold text-gray-900">Job Postings</h3>
        </div>
        <div className="ml-4 mt-2 shrink-0">
          <button
            type="button"
            className="relative inline-flex items-center rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
          >
            Create new job
          </button>
        </div>
      </div>
    </div>
  )
}
