// v4/light/vue/application-ui/layout/dividers/With title.vue
<template>
  <div class="flex items-center">
    <div class="w-full border-t border-gray-300" aria-hidden="true" />
    <div class="relative flex justify-center">
      <span class="bg-white px-3 text-base font-semibold text-gray-900">Projects</span>
    </div>
    <div class="w-full border-t border-gray-300" aria-hidden="true" />
  </div>
</template>

// v3/dark/react/application-ui/layout/dividers/With title.jsx
export default function Example() {
  return (
    <div className="flex items-center">
      <div aria-hidden="true" className="w-full border-t border-white/15" />
      <div className="relative flex justify-center">
        <span className="bg-gray-900 px-3 text-base font-semibold text-white">Projects</span>
      </div>
      <div aria-hidden="true" className="w-full border-t border-white/15" />
    </div>
  )
}
