// v3/dark/vue/application-ui/forms/action-panels/With link.vue
<template>
  <div class="bg-gray-800/50 outline outline-1 -outline-offset-1 outline-white/10 sm:rounded-lg">
    <div class="px-4 py-5 sm:p-6">
      <h3 class="text-base font-semibold text-white">Continuous Integration</h3>
      <div class="mt-2 max-w-xl text-sm text-gray-400">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, totam at reprehenderit maxime aut beatae ad.</p>
      </div>
      <div class="mt-3 text-sm/6">
        <a href="#" class="font-semibold text-indigo-400 hover:text-indigo-300">
          Learn more about our CI features
          <span aria-hidden="true"> &rarr;</span>
        </a>
      </div>
    </div>
  </div>
</template>

// v4/dark/react/application-ui/forms/action-panels/With link.jsx
export default function Example() {
  return (
    <div className="bg-gray-800/50 outline -outline-offset-1 outline-white/10 sm:rounded-lg">
      <div className="px-4 py-5 sm:p-6">
        <h3 className="text-base font-semibold text-white">Continuous Integration</h3>
        <div className="mt-2 max-w-xl text-sm text-gray-400">
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Commodi, totam at reprehenderit maxime aut beatae
            ad.
          </p>
        </div>
        <div className="mt-3 text-sm/6">
          <a href="#" className="font-semibold text-indigo-400 hover:text-indigo-300">
            Learn more about our CI features
            <span aria-hidden="true"> &rarr;</span>
          </a>
        </div>
      </div>
    </div>
  )
}
