// v3/dark/vue/application-ui/headings/card-headings/With description and action.vue
<template>
  <div class="border-b border-white/10 px-4 py-5 sm:px-6">
    <div class="-ml-4 -mt-4 flex flex-wrap items-center justify-between sm:flex-nowrap">
      <div class="ml-4 mt-4">
        <h3 class="text-base font-semibold text-white">Job Postings</h3>
        <p class="mt-1 text-sm text-gray-400">Lorem ipsum dolor sit amet consectetur adipisicing elit quam corrupti consectetur.</p>
      </div>
      <div class="ml-4 mt-4 shrink-0">
        <button type="button" class="relative inline-flex items-center rounded-md bg-indigo-500 px-3 py-2 text-sm font-semibold text-white hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500">Create new job</button>
      </div>
    </div>
  </div>
</template>

// v3/dark/react/application-ui/headings/card-headings/With description and action.jsx
export default function Example() {
  return (
    <div className="border-b border-white/10 px-4 py-5 sm:px-6">
      <div className="-ml-4 -mt-4 flex flex-wrap items-center justify-between sm:flex-nowrap">
        <div className="ml-4 mt-4">
          <h3 className="text-base font-semibold text-white">Job Postings</h3>
          <p className="mt-1 text-sm text-gray-400">
            Lorem ipsum dolor sit amet consectetur adipisicing elit quam corrupti consectetur.
          </p>
        </div>
        <div className="ml-4 mt-4 shrink-0">
          <button
            type="button"
            className="relative inline-flex items-center rounded-md bg-indigo-500 px-3 py-2 text-sm font-semibold text-white hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500"
          >
            Create new job
          </button>
        </div>
      </div>
    </div>
  )
}
