// react-v3/ecommerce/components/promo-sections/FullwidthWithOverlappingImageTiles.jsx
export default function Example() {
  return (
    <div className="bg-white">
      <div className="overflow-hidden pt-32 sm:pt-14">
        <div className="bg-gray-800">
          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div className="relative pb-16 pt-48 sm:pb-24">
              <div>
                <h2 id="sale-heading" className="text-4xl font-bold tracking-tight text-white md:text-5xl">
                  Final Stock.
                  <br />
                  Up to 50% off.
                </h2>
                <div className="mt-6 text-base">
                  <a href="#" className="font-semibold text-white">
                    Shop the sale
                    <span aria-hidden="true"> &rarr;</span>
                  </a>
                </div>
              </div>

              <div className="absolute -top-32 left-1/2 min-w-max -translate-x-1/2 transform sm:top-6 sm:translate-x-0">
                <div className="ml-24 flex space-x-6 sm:ml-3 lg:space-x-8">
                  <div className="flex space-x-6 sm:flex-col sm:space-x-0 sm:space-y-6 lg:space-y-8">
                    <div className="shrink-0">
                      <img
                        alt=""
                        src="/plus-assets/img/ecommerce-images/home-page-03-category-01.jpg"
                        className="size-64 rounded-lg object-cover md:size-72"
                      />
                    </div>

                    <div className="mt-6 shrink-0 sm:mt-0">
                      <img
                        alt=""
                        src="/plus-assets/img/ecommerce-images/home-page-03-category-02.jpg"
                        className="size-64 rounded-lg object-cover md:size-72"
                      />
                    </div>
                  </div>
                  <div className="flex space-x-6 sm:-mt-20 sm:flex-col sm:space-x-0 sm:space-y-6 lg:space-y-8">
                    <div className="shrink-0">
                      <img
                        alt=""
                        src="/plus-assets/img/ecommerce-images/home-page-03-favorite-01.jpg"
                        className="size-64 rounded-lg object-cover md:size-72"
                      />
                    </div>

                    <div className="mt-6 shrink-0 sm:mt-0">
                      <img
                        alt=""
                        src="/plus-assets/img/ecommerce-images/home-page-03-favorite-02.jpg"
                        className="size-64 rounded-lg object-cover md:size-72"
                      />
                    </div>
                  </div>
                  <div className="flex space-x-6 sm:flex-col sm:space-x-0 sm:space-y-6 lg:space-y-8">
                    <div className="shrink-0">
                      <img
                        alt=""
                        src="/plus-assets/img/ecommerce-images/home-page-03-category-01.jpg"
                        className="size-64 rounded-lg object-cover md:size-72"
                      />
                    </div>

                    <div className="mt-6 shrink-0 sm:mt-0">
                      <img
                        alt=""
                        src="/plus-assets/img/ecommerce-images/home-page-03-category-02.jpg"
                        className="size-64 rounded-lg object-cover md:size-72"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// v4/light/vue/ecommerce/components/promo-sections/Full-width with overlapping image tiles.vue
<template>
  <div class="bg-white">
    <div class="overflow-hidden pt-32 sm:pt-14">
      <div class="bg-gray-800">
        <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div class="relative pt-48 pb-16 sm:pb-24">
            <div>
              <h2 id="sale-heading" class="text-4xl font-bold tracking-tight text-white md:text-5xl">
                Final Stock.
                <br />
                Up to 50% off.
              </h2>
              <div class="mt-6 text-base">
                <a href="#" class="font-semibold text-white">
                  Shop the sale
                  <span aria-hidden="true"> &rarr;</span>
                </a>
              </div>
            </div>

            <div class="absolute -top-32 left-1/2 min-w-max -translate-x-1/2 transform sm:top-6 sm:translate-x-0">
              <div class="ml-24 flex space-x-6 sm:ml-3 lg:space-x-8">
                <div class="flex space-x-6 sm:flex-col sm:space-y-6 sm:space-x-0 lg:space-y-8">
                  <div class="shrink-0">
                    <img class="size-64 rounded-lg object-cover md:size-72" src="/plus-assets/img/ecommerce-images/home-page-03-category-01.jpg" alt="" />
                  </div>

                  <div class="mt-6 shrink-0 sm:mt-0">
                    <img class="size-64 rounded-lg object-cover md:size-72" src="/plus-assets/img/ecommerce-images/home-page-03-category-02.jpg" alt="" />
                  </div>
                </div>
                <div class="flex space-x-6 sm:-mt-20 sm:flex-col sm:space-y-6 sm:space-x-0 lg:space-y-8">
                  <div class="shrink-0">
                    <img class="size-64 rounded-lg object-cover md:size-72" src="/plus-assets/img/ecommerce-images/home-page-03-favorite-01.jpg" alt="" />
                  </div>

                  <div class="mt-6 shrink-0 sm:mt-0">
                    <img class="size-64 rounded-lg object-cover md:size-72" src="/plus-assets/img/ecommerce-images/home-page-03-favorite-02.jpg" alt="" />
                  </div>
                </div>
                <div class="flex space-x-6 sm:flex-col sm:space-y-6 sm:space-x-0 lg:space-y-8">
                  <div class="shrink-0">
                    <img class="size-64 rounded-lg object-cover md:size-72" src="/plus-assets/img/ecommerce-images/home-page-03-category-01.jpg" alt="" />
                  </div>

                  <div class="mt-6 shrink-0 sm:mt-0">
                    <img class="size-64 rounded-lg object-cover md:size-72" src="/plus-assets/img/ecommerce-images/home-page-03-category-02.jpg" alt="" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
