// v3/light/react/application-ui/layout/dividers/With title on left.jsx
export default function Example() {
  return (
    <div className="flex items-center">
      <div className="relative flex justify-start">
        <span className="bg-white pr-3 text-base font-semibold text-gray-900">Projects</span>
      </div>
      <div aria-hidden="true" className="w-full border-t border-gray-300" />
    </div>
  )
}

// v4/system/vue/application-ui/layout/dividers/With title on left.vue
<template>
  <div class="flex items-center">
    <div class="relative flex justify-start">
      <span class="bg-white pr-3 text-base font-semibold text-gray-900 dark:bg-gray-900 dark:text-white">Projects</span>
    </div>
    <div class="w-full border-t border-gray-300 dark:border-white/15" aria-hidden="true" />
  </div>
</template>
