// v3/dark/vue/application-ui/elements/badges/Small pill with border.vue
<template>
  <span class="inline-flex items-center rounded-full bg-gray-400/10 px-1.5 py-0.5 text-xs font-medium text-gray-400 ring-1 ring-inset ring-gray-400/20">Badge</span>
  <span class="inline-flex items-center rounded-full bg-red-900/20 px-1.5 py-0.5 text-xs font-medium text-red-400 ring-1 ring-inset ring-red-400/20">Badge</span>
  <span class="inline-flex items-center rounded-full bg-yellow-900/20 px-1.5 py-0.5 text-xs font-medium text-yellow-500 ring-1 ring-inset ring-yellow-400/20">Badge</span>
  <span class="inline-flex items-center rounded-full bg-green-900/20 px-1.5 py-0.5 text-xs font-medium text-green-400 ring-1 ring-inset ring-green-500/20">Badge</span>
  <span class="inline-flex items-center rounded-full bg-blue-900/20 px-1.5 py-0.5 text-xs font-medium text-blue-400 ring-1 ring-inset ring-blue-400/30">Badge</span>
  <span class="inline-flex items-center rounded-full bg-indigo-900/20 px-1.5 py-0.5 text-xs font-medium text-indigo-400 ring-1 ring-inset ring-indigo-400/30">Badge</span>
  <span class="inline-flex items-center rounded-full bg-purple-900/20 px-1.5 py-0.5 text-xs font-medium text-purple-400 ring-1 ring-inset ring-purple-400/30">Badge</span>
  <span class="inline-flex items-center rounded-full bg-pink-900/20 px-1.5 py-0.5 text-xs font-medium text-pink-400 ring-1 ring-inset ring-pink-400/20">Badge</span>
</template>

// v4/dark/react/application-ui/elements/badges/Small pill with border.jsx
export default function Example() {
  return (
    <>
      <span className="inline-flex items-center rounded-full bg-gray-400/10 px-1.5 py-0.5 text-xs font-medium text-gray-400 inset-ring inset-ring-gray-400/20">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-red-900/20 px-1.5 py-0.5 text-xs font-medium text-red-400 inset-ring inset-ring-red-400/20">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-yellow-900/20 px-1.5 py-0.5 text-xs font-medium text-yellow-500 inset-ring inset-ring-yellow-400/20">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-green-900/20 px-1.5 py-0.5 text-xs font-medium text-green-400 inset-ring inset-ring-green-500/20">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-blue-900/20 px-1.5 py-0.5 text-xs font-medium text-blue-400 inset-ring inset-ring-blue-400/30">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-indigo-900/20 px-1.5 py-0.5 text-xs font-medium text-indigo-400 inset-ring inset-ring-indigo-400/30">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-purple-900/20 px-1.5 py-0.5 text-xs font-medium text-purple-400 inset-ring inset-ring-purple-400/30">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-pink-900/20 px-1.5 py-0.5 text-xs font-medium text-pink-400 inset-ring inset-ring-pink-400/20">
        Badge
      </span>
    </>
  )
}
