// v4/dark/react/application-ui/layout/list-containers/Flat card with dividers.jsx
const items = [{ id: 1 }, { id: 2 }, { id: 3 }]

export default function Example() {
  return (
    <div className="overflow-hidden rounded-md border border-white/10 bg-gray-900">
      <ul role="list" className="divide-y divide-white/10">
        {items.map((item) => (
          <li key={item.id} className="px-6 py-4">
            {/* Your content */}
          </li>
        ))}
      </ul>
    </div>
  )
}

// v4/light/vue/application-ui/layout/list-containers/Flat card with dividers.vue
<template>
  <div class="overflow-hidden rounded-md border border-gray-300 bg-white">
    <ul role="list" class="divide-y divide-gray-300">
      <li v-for="item in items" :key="item.id" class="px-6 py-4">
        <!-- Your content -->
      </li>
    </ul>
  </div>
</template>

<script setup>
const items = [{ id: 1 }, { id: 2 }, { id: 3 }]
</script>
