// v3/dark/vue/application-ui/forms/radio-groups/Stacked cards.vue
<template>
  <fieldset aria-label="Server size">
    <div class="space-y-4">
      <label v-for="plan in plans" :key="plan.id" :aria-label="plan.name" :aria-description="`${plan.ram}, ${plan.cpus}, ${plan.disk}, ${plan.price} per month`" class="group relative block rounded-lg border border-white/10 bg-gray-800/50 px-6 py-4 has-[:checked]:outline has-[:focus-visible]:outline has-[:checked]:outline-2 has-[:focus-visible]:outline-[3px] has-[:checked]:-outline-offset-2 has-[:focus-visible]:-outline-offset-1 has-[:checked]:outline-indigo-500 sm:flex sm:justify-between">
        <input type="radio" name="plan" :value="plan.id" :checked="plan.id === 'hobby'" class="absolute inset-0 appearance-none focus:outline focus:outline-0" />
        <span class="flex items-center">
          <span class="flex flex-col text-sm">
            <span class="font-medium text-white">{{ plan.name }}</span>
            <span class="text-gray-400">
              <span class="block sm:inline">{{ plan.ram }} / {{ plan.cpus }}</span>
              {{ ' ' }}
              <span class="hidden sm:mx-1 sm:inline" aria-hidden="true">&middot;</span>
              {{ ' ' }}
              <span class="block sm:inline">{{ plan.disk }}</span>
            </span>
          </span>
        </span>
        <span class="mt-2 flex text-sm sm:ml-4 sm:mt-0 sm:flex-col sm:text-right">
          <span class="font-medium text-white">{{ plan.price }}</span>
          <span class="ml-1 text-gray-400 sm:ml-0">/mo</span>
        </span>
      </label>
    </div>
  </fieldset>
</template>

<script setup>
const plans = [
  { id: 'hobby', name: 'Hobby', ram: '8GB', cpus: '4 CPUs', disk: '160 GB SSD disk', price: '$40' },
  { id: 'startup', name: 'Startup', ram: '12GB', cpus: '6 CPUs', disk: '256 GB SSD disk', price: '$80' },
  { id: 'business', name: 'Business', ram: '16GB', cpus: '8 CPUs', disk: '512 GB SSD disk', price: '$160' },
  { id: 'enterprise', name: 'Enterprise', ram: '32GB', cpus: '12 CPUs', disk: '1024 GB SSD disk', price: '$240' },
]
</script>

// v3/dark/react/application-ui/forms/radio-groups/Stacked cards.jsx
const plans = [
  { id: 'hobby', name: 'Hobby', ram: '8GB', cpus: '4 CPUs', disk: '160 GB SSD disk', price: '$40' },
  { id: 'startup', name: 'Startup', ram: '12GB', cpus: '6 CPUs', disk: '256 GB SSD disk', price: '$80' },
  { id: 'business', name: 'Business', ram: '16GB', cpus: '8 CPUs', disk: '512 GB SSD disk', price: '$160' },
  { id: 'enterprise', name: 'Enterprise', ram: '32GB', cpus: '12 CPUs', disk: '1024 GB SSD disk', price: '$240' },
]

export default function Example() {
  return (
    <fieldset aria-label="Server size">
      <div className="space-y-4">
        {plans.map((plan) => (
          <label
            key={plan.id}
            aria-label={plan.name}
            aria-description={`${plan.ram}, ${plan.cpus}, ${plan.disk}, ${plan.price} per month`}
            className="group relative block rounded-lg border border-white/10 bg-gray-800/50 px-6 py-4 has-[:checked]:outline has-[:focus-visible]:outline has-[:checked]:outline-2 has-[:focus-visible]:outline-[3px] has-[:checked]:-outline-offset-2 has-[:focus-visible]:-outline-offset-1 has-[:checked]:outline-indigo-500 sm:flex sm:justify-between"
          >
            <input
              defaultValue={plan.id}
              defaultChecked={plan.id === 'hobby'}
              name="plan"
              type="radio"
              className="absolute inset-0 appearance-none focus:outline focus:outline-0"
            />
            <span className="flex items-center">
              <span className="flex flex-col text-sm">
                <span className="font-medium text-white">{plan.name}</span>
                <span className="text-gray-400">
                  <span className="block sm:inline">
                    {plan.ram} / {plan.cpus}
                  </span>{' '}
                  <span aria-hidden="true" className="hidden sm:mx-1 sm:inline">
                    &middot;
                  </span>{' '}
                  <span className="block sm:inline">{plan.disk}</span>
                </span>
              </span>
            </span>
            <span className="mt-2 flex text-sm sm:ml-4 sm:mt-0 sm:flex-col sm:text-right">
              <span className="font-medium text-white">{plan.price}</span>
              <span className="ml-1 text-gray-400 sm:ml-0">/mo</span>
            </span>
          </label>
        ))}
      </div>
    </fieldset>
  )
}
