// v3/dark/vue/marketing/sections/cta-sections/Simple justified on subtle brand.vue
<template>
  <div class="bg-indigo-950">
    <div class="mx-auto max-w-7xl px-6 py-24 sm:py-32 lg:flex lg:items-center lg:justify-between lg:px-8">
      <h2 class="max-w-2xl text-4xl font-semibold tracking-tight text-white sm:text-5xl">
        Ready to dive in?
        <br />
        Start your free trial today.
      </h2>
      <div class="mt-10 flex items-center gap-x-6 lg:mt-0 lg:shrink-0">
        <a href="#" class="rounded-md bg-indigo-500 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500"> Get started </a>
        <a href="#" class="text-sm/6 font-semibold text-gray-100">
          Learn more
          <span aria-hidden="true">→</span>
        </a>
      </div>
    </div>
  </div>
</template>

// v4/dark/react/marketing/sections/cta-sections/Simple justified on subtle brand.jsx
export default function Example() {
  return (
    <div className="bg-indigo-950">
      <div className="mx-auto max-w-7xl px-6 py-24 sm:py-32 lg:flex lg:items-center lg:justify-between lg:px-8">
        <h2 className="max-w-2xl text-4xl font-semibold tracking-tight text-white sm:text-5xl">
          Ready to dive in?
          <br />
          Start your free trial today.
        </h2>
        <div className="mt-10 flex items-center gap-x-6 lg:mt-0 lg:shrink-0">
          <a
            href="#"
            className="rounded-md bg-indigo-500 px-3.5 py-2.5 text-sm font-semibold text-white shadow-xs hover:bg-indigo-400 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500"
          >
            {' '}
            Get started{' '}
          </a>
          <a href="#" className="text-sm/6 font-semibold text-gray-100">
            Learn more
            <span aria-hidden="true">→</span>
          </a>
        </div>
      </div>
    </div>
  )
}
