// v3/dark/react/application-ui/headings/section-headings/With label.jsx
export default function Example() {
  return (
    <div className="border-b border-white/10 pb-5">
      <div className="-ml-2 -mt-2 flex flex-wrap items-baseline">
        <h3 className="ml-2 mt-2 text-base font-semibold text-white">Job Postings</h3>
        <p className="ml-2 mt-1 truncate text-sm text-gray-400">in Engineering</p>
      </div>
    </div>
  )
}

// v3/dark/vue/application-ui/headings/section-headings/With label.vue
<template>
  <div class="border-b border-white/10 pb-5">
    <div class="-ml-2 -mt-2 flex flex-wrap items-baseline">
      <h3 class="ml-2 mt-2 text-base font-semibold text-white">Job Postings</h3>
      <p class="ml-2 mt-1 truncate text-sm text-gray-400">in Engineering</p>
    </div>
  </div>
</template>
