// v4/light/react/application-ui/elements/badges/Small pill with border.jsx
export default function Example() {
  return (
    <>
      <span className="inline-flex items-center rounded-full bg-gray-50 px-1.5 py-0.5 text-xs font-medium text-gray-600 inset-ring inset-ring-gray-500/10">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-red-50 px-1.5 py-0.5 text-xs font-medium text-red-700 inset-ring inset-ring-red-600/10">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-yellow-50 px-1.5 py-0.5 text-xs font-medium text-yellow-800 inset-ring inset-ring-yellow-600/20">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-green-50 px-1.5 py-0.5 text-xs font-medium text-green-700 inset-ring inset-ring-green-600/20">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-blue-50 px-1.5 py-0.5 text-xs font-medium text-blue-700 inset-ring inset-ring-blue-700/10">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-indigo-50 px-1.5 py-0.5 text-xs font-medium text-indigo-700 inset-ring inset-ring-indigo-700/10">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-purple-50 px-1.5 py-0.5 text-xs font-medium text-purple-700 inset-ring inset-ring-purple-700/10">
        Badge
      </span>
      <span className="inline-flex items-center rounded-full bg-pink-50 px-1.5 py-0.5 text-xs font-medium text-pink-700 inset-ring inset-ring-pink-700/10">
        Badge
      </span>
    </>
  )
}

// v3/dark/vue/application-ui/elements/badges/Small pill with border.vue
<template>
  <span class="inline-flex items-center rounded-full bg-gray-400/10 px-1.5 py-0.5 text-xs font-medium text-gray-400 ring-1 ring-inset ring-gray-400/20">Badge</span>
  <span class="inline-flex items-center rounded-full bg-red-900/20 px-1.5 py-0.5 text-xs font-medium text-red-400 ring-1 ring-inset ring-red-400/20">Badge</span>
  <span class="inline-flex items-center rounded-full bg-yellow-900/20 px-1.5 py-0.5 text-xs font-medium text-yellow-500 ring-1 ring-inset ring-yellow-400/20">Badge</span>
  <span class="inline-flex items-center rounded-full bg-green-900/20 px-1.5 py-0.5 text-xs font-medium text-green-400 ring-1 ring-inset ring-green-500/20">Badge</span>
  <span class="inline-flex items-center rounded-full bg-blue-900/20 px-1.5 py-0.5 text-xs font-medium text-blue-400 ring-1 ring-inset ring-blue-400/30">Badge</span>
  <span class="inline-flex items-center rounded-full bg-indigo-900/20 px-1.5 py-0.5 text-xs font-medium text-indigo-400 ring-1 ring-inset ring-indigo-400/30">Badge</span>
  <span class="inline-flex items-center rounded-full bg-purple-900/20 px-1.5 py-0.5 text-xs font-medium text-purple-400 ring-1 ring-inset ring-purple-400/30">Badge</span>
  <span class="inline-flex items-center rounded-full bg-pink-900/20 px-1.5 py-0.5 text-xs font-medium text-pink-400 ring-1 ring-inset ring-pink-400/20">Badge</span>
</template>
