// v4/system/vue/application-ui/navigation/progress-bars/Progress bar.vue
<template>
  <div>
    <h4 class="sr-only">Status</h4>
    <p class="text-sm font-medium text-gray-900 dark:text-white">Migrating MySQL database...</p>
    <div class="mt-6" aria-hidden="true">
      <div class="overflow-hidden rounded-full bg-gray-200 dark:bg-white/10">
        <div class="h-2 rounded-full bg-indigo-600 dark:bg-indigo-500" style="width: 37.5%" />
      </div>
      <div class="mt-6 hidden grid-cols-4 text-sm font-medium text-gray-600 sm:grid dark:text-gray-400">
        <div class="text-indigo-600 dark:text-indigo-400">Copying files</div>
        <div class="text-center text-indigo-600 dark:text-indigo-400">Migrating database</div>
        <div class="text-center">Compiling assets</div>
        <div class="text-right">Deployed</div>
      </div>
    </div>
  </div>
</template>

// v3/dark/react/application-ui/navigation/progress-bars/Progress bar.jsx
export default function Example() {
  return (
    <div>
      <h4 className="sr-only">Status</h4>
      <p className="text-sm font-medium text-white">Migrating MySQL database...</p>
      <div aria-hidden="true" className="mt-6">
        <div className="overflow-hidden rounded-full bg-white/10">
          <div style={{ width: '37.5%' }} className="h-2 rounded-full bg-indigo-500" />
        </div>
        <div className="mt-6 hidden grid-cols-4 text-sm font-medium text-gray-400 sm:grid">
          <div className="text-indigo-400">Copying files</div>
          <div className="text-center text-indigo-400">Migrating database</div>
          <div className="text-center">Compiling assets</div>
          <div className="text-right">Deployed</div>
        </div>
      </div>
    </div>
  )
}
