// v3/dark/vue/application-ui/headings/section-headings/With action.vue
<template>
  <div class="border-b border-white/10 pb-5 sm:flex sm:items-center sm:justify-between">
    <h3 class="text-base font-semibold text-white">Job Postings</h3>
    <div class="mt-3 sm:ml-4 sm:mt-0">
      <button type="button" class="inline-flex items-center rounded-md bg-indigo-500 px-3 py-2 text-sm font-semibold text-white hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500">Create new job</button>
    </div>
  </div>
</template>

// v3/dark/react/application-ui/headings/section-headings/With action.jsx
export default function Example() {
  return (
    <div className="border-b border-white/10 pb-5 sm:flex sm:items-center sm:justify-between">
      <h3 className="text-base font-semibold text-white">Job Postings</h3>
      <div className="mt-3 sm:ml-4 sm:mt-0">
        <button
          type="button"
          className="inline-flex items-center rounded-md bg-indigo-500 px-3 py-2 text-sm font-semibold text-white hover:bg-indigo-400 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500"
        >
          Create new job
        </button>
      </div>
    </div>
  )
}
