// v3/light/react/application-ui/elements/avatars/Circular avatars with bottom notification.jsx
export default function Example() {
  return (
    <>
      <span className="relative inline-block">
        <img
          alt=""
          src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
          className="size-6 rounded-full outline outline-1 -outline-offset-1 outline-black/5"
        />
        <span className="absolute bottom-0 right-0 block size-1.5 rounded-full bg-gray-300 ring-2 ring-white" />
      </span>

      <span className="relative inline-block">
        <img
          alt=""
          src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
          className="size-8 rounded-full outline outline-1 -outline-offset-1 outline-black/5"
        />
        <span className="absolute bottom-0 right-0 block size-2 rounded-full bg-red-400 ring-2 ring-white" />
      </span>

      <span className="relative inline-block">
        <img
          alt=""
          src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
          className="size-10 rounded-full outline outline-1 -outline-offset-1 outline-black/5"
        />
        <span className="absolute bottom-0 right-0 block size-2.5 rounded-full bg-green-400 ring-2 ring-white" />
      </span>

      <span className="relative inline-block">
        <img
          alt=""
          src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
          className="size-12 rounded-full outline outline-1 -outline-offset-1 outline-black/5"
        />
        <span className="absolute bottom-0 right-0 block size-3 rounded-full bg-gray-300 ring-2 ring-white" />
      </span>

      <span className="relative inline-block">
        <img
          alt=""
          src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
          className="size-14 rounded-full outline outline-1 -outline-offset-1 outline-black/5"
        />
        <span className="absolute bottom-0 right-0 block size-3.5 rounded-full bg-red-400 ring-2 ring-white" />
      </span>

      <span className="relative inline-block">
        <img
          alt=""
          src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
          className="size-16 rounded-full outline outline-1 -outline-offset-1 outline-black/5"
        />
        <span className="absolute bottom-0 right-0 block size-4 rounded-full bg-green-400 ring-2 ring-white" />
      </span>
    </>
  )
}

// v3/light/vue/application-ui/elements/avatars/Circular avatars with bottom notification.vue
<template>
  <span class="relative inline-block">
    <img class="size-6 rounded-full outline outline-1 -outline-offset-1 outline-black/5" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
    <span class="absolute bottom-0 right-0 block size-1.5 rounded-full bg-gray-300 ring-2 ring-white" />
  </span>

  <span class="relative inline-block">
    <img class="size-8 rounded-full outline outline-1 -outline-offset-1 outline-black/5" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
    <span class="absolute bottom-0 right-0 block size-2 rounded-full bg-red-400 ring-2 ring-white" />
  </span>

  <span class="relative inline-block">
    <img class="size-10 rounded-full outline outline-1 -outline-offset-1 outline-black/5" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
    <span class="absolute bottom-0 right-0 block size-2.5 rounded-full bg-green-400 ring-2 ring-white" />
  </span>

  <span class="relative inline-block">
    <img class="size-12 rounded-full outline outline-1 -outline-offset-1 outline-black/5" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
    <span class="absolute bottom-0 right-0 block size-3 rounded-full bg-gray-300 ring-2 ring-white" />
  </span>

  <span class="relative inline-block">
    <img class="size-14 rounded-full outline outline-1 -outline-offset-1 outline-black/5" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
    <span class="absolute bottom-0 right-0 block size-3.5 rounded-full bg-red-400 ring-2 ring-white" />
  </span>

  <span class="relative inline-block">
    <img class="size-16 rounded-full outline outline-1 -outline-offset-1 outline-black/5" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
    <span class="absolute bottom-0 right-0 block size-4 rounded-full bg-green-400 ring-2 ring-white" />
  </span>
</template>
